### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by jadyhome** [jadyhome/blooming#1]
-- Error Message: 
<img width="350" alt="cors error" src="https://user-images.githubusercontent.com/71613633/96465676-393faa00-11f7-11eb-8b60-d5e1e81d182c.png">

-- Description: trying to see that the data is working on the console.log
-- Expected Output: the data showing up on the console.log
-- Actual Output: the error message on the console.log

**Comment by anpato** [comment]
MosefCors Should take care of that for you, you can go ahead and close out this issue!
